# Generated by Django 3.2.4 on 2021-07-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0002_auto_20210730_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='expires',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='hash',
            field=models.CharField(default='AHeDbkE', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
