# Generated by Django 3.2.4 on 2021-07-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0003_auto_20210730_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='hash',
            field=models.CharField(default='T2mK4qg', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
