# Generated by Django 3.2.4 on 2021-07-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0004_auto_20210730_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='hash',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
