# Generated by Django 3.2.4 on 2021-07-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0006_alter_shorturl_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='hash',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
