# Generated by Django 3.2.4 on 2021-07-31 07:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0009_alter_shorturl_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='hash',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
